spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=helaketha_agri;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=asdf12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
