spring:
  datasource:
    url: jdbc:mysql://localhost:3306/helaketha_agri?createDatabaseIfNotExist=true
    username: dbuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/your-realm
          jwk-set-uri: http://localhost:8080/realms/your-realm/protocol/openid-connect/certs

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

server:
  port: 10187

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
  allowed-headers: "*"
